import AuthProvider from './AuthProvider';
import './globals.css'
import NavMenu from './NavMenu'
import { Open_Sans } from 'next/font/google';
const myFont = Open_Sans({ weight: '400', subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={myFont.className}>
          <NavMenu/>
          <main>{children}</main>
        </body>
      </html>
    </AuthProvider>
  )
}
